import { Player } from '../player/Player.js';
import { Zombie } from '../enemies/Zombie.js';
import { MapManager } from '../world/MapManager.js';
import { SaveSystem } from './SaveSystem.js';
import { Input } from './Input.js';
import { Camera } from './Camera.js';
import { AudioManager } from './AudioManager.js';
import { Settings } from './Settings.js';
import { DayNightSystem } from '../systems/DayNightSystem.js';
import { HordeSystem } from '../systems/HordeSystem.js';
import { BuildingSystem } from '../systems/BuildingSystem.js';
import { CraftingSystem, RECIPES } from '../systems/CraftingSystem.js';
import { NPCSystem } from '../systems/NPCSystem.js';
import { QuestSystem, QUESTS } from '../systems/QuestSystem.js';
import { BaseUpgradeSystem } from '../systems/BaseUpgradeSystem.js';
import { SurvivalSystem } from '../systems/SurvivalSystem.js';
import { UpgradeSystem, UPGRADES } from '../systems/UpgradeSystem.js';
import { BaseFacilitiesSystem, FACILITY_ITEMS, FACILITY_LABELS } from '../systems/BaseFacilitiesSystem.js';
import { WEAPONS } from '../weapons/WeaponSystem.js';
const $ = id => document.getElementById(id);

export class Game {
  constructor(canvas, assets) {
    this.c = canvas;this.a = assets;this.settings = Settings.load();
    const [width,height] = this.settings.resolution.split('x').map(Number);canvas.width=width;canvas.height=height;
    this.quality=this.settings.quality==='auto'?(navigator.hardwareConcurrency<=4?'low':'medium'):this.settings.quality;
    this.g=canvas.getContext('2d',{alpha:false});this.audio=new AudioManager();this.input=new Input(canvas);this.camera=new Camera(width,height);
    this.save=SaveSystem.load();this.maps=new MapManager({currentArea:this.save.currentArea,areas:this.save.maps,legacyWorld:this.save.world||{baseHp:this.save.baseHp}});this.world=this.maps.enter();this.player=new Player(1100,860,this.save.player);
    this.dayNight=new DayNightSystem(this.save.dayNight??this.save.worldTime);this.horde=new HordeSystem(this.save.horde);this.building=new BuildingSystem();this.crafting=new CraftingSystem();this.npcs=new NPCSystem();this.quests=new QuestSystem(this.save.quests);this.baseUpgrades=new BaseUpgradeSystem();this.survival=new SurvivalSystem(this.save.survival);this.upgradeSystem=new UpgradeSystem();this.facilities=new BaseFacilitiesSystem(this.save.facilities);
    this.zombies=[];this.kills=this.save.kills||0;this.spawnTimer=0;this.paused=false;this.transitioning=false;this.toastTimer=0;this.alertTimer=0;this.saveTimer=0;this.spawnPopulation();
    if(this.horde.active&&this.maps.currentId==='base')for(let i=0;i<8;i++)this.spawnZombie(i%4===0?'brute':i%3===0?'runner':'walker',true);
    addEventListener('beforeunload',()=>this.persist());
  }
  start(){this.last=performance.now();requestAnimationFrame(time=>this.loop(time))}
  spawnPopulation(){const base=this.quality==='low'?6:this.quality==='high'?13:9,amount=Math.max(3,Math.round(base*this.world.population));for(let i=0;i<amount;i++)this.spawnZombie(i===5?'brute':i%4===0?'runner':'walker')}
  async changeMap(exit){if(this.transitioning)return;if(this.maps.currentId==='base'&&this.horde.active&&exit.to!=='base'){this.player.x=Math.min(this.player.x,2000);this.toast('A saída está bloqueada durante a horda');return}this.transitioning=true;this.paused=true;const loading=$('loading');$('loadTitle').textContent=`CARREGANDO: ${this.maps.name(exit.to).toUpperCase()}`;$('loadFill').style.width='0%';$('loadText').textContent='0%';loading.classList.add('active');try{await this.a.loadArea(exit.to,p=>{$('loadFill').style.width=`${p}%`;$('loadText').textContent=`${p}%`});this.maps.store(this.world);this.a.activateArea(exit.to);this.world=this.maps.enter(exit.to);this.player.x=exit.spawn.x;this.player.y=exit.spawn.y;this.player.action('interact');this.zombies.length=0;this.spawnPopulation();if(exit.to==='base'&&this.horde.active)for(let i=0;i<8;i++)this.spawnZombie(i%4===0?'brute':i%3===0?'runner':'walker',true);this.camera.x=0;this.camera.y=0;this.camera.follow(this.player,this.world,1);this.persist();$('areaName').textContent=this.maps.name()}catch(error){this.toast(`Falha ao carregar mapa: ${error.message}`)}finally{loading.classList.remove('active');this.paused=false;this.transitioning=false}}
  loop(time){const dt=Math.min((time-this.last)/1000,.033);this.last=time;if(!this.paused)this.update(dt);this.draw();requestAnimationFrame(next=>this.loop(next))}
  spawnZombie(type,hordeSpawn=false){const edge=Math.floor(Math.random()*4),pad=this.world.margin+35;const x=edge===1?this.world.w-pad:edge===3?pad:pad+Math.random()*(this.world.w-pad*2);const y=edge===0?pad:edge===2?this.world.h-pad:pad+Math.random()*(this.world.h-pad*2);const z=new Zombie(x,y,type||Math.random()<.12?'brute':Math.random()<.32?'runner':'walker');z.hordeSpawn=hordeSpawn;this.zombies.push(z)}
  selectBuild(type){this.building.toggle(type);this.paused=false;$('buildHint').classList.toggle('show',!!this.building.mode);$('buildToolbar').classList.toggle('show',!!this.building.mode)}
  update(dt){
    this.spawnTimer+=dt;this.saveTimer+=dt;this.toastTimer-=dt;this.alertTimer-=dt;
    const hordeHere=this.maps.currentId==='base'&&this.horde.active,maxZombies=this.quality==='low'?12:this.quality==='high'?22:17;if(this.spawnTimer>(this.dayNight.night?3.8:6.5)&&this.zombies.length<maxZombies&&!hordeHere){this.spawnTimer=0;this.spawnZombie()}
    this.world.update(dt);if(this.maps.currentId==='base')this.npcs.update(dt);this.dayNight.update(dt);this.player.update(dt,this.input,this.world);if(this.survival.update(dt,this.player))this.toast('Fome crítica: encontre e consuma comida');this.camera.follow(this.player,this.world,dt);const exit=this.maps.transitionAt(this.player);if(exit){this.input.endFrame();this.changeMap(exit);return}
    const weaponKeys=['bat','pistol','axe','machete','shotgun','rifle'];for(let i=0;i<weaponKeys.length;i++)if(this.input.consume(String(i+1)))this.player.weapon.switch(weaponKeys[i]);if(this.input.consume('r'))this.player.weapon.reload();
    if(this.input.consume('i'))this.toggleInventory(true);if(this.input.consume('c'))this.toggleCrafting(true);if(this.input.consume('q'))this.toggleArsenal(true);if(this.input.consume('u'))this.toggleUpgrades(true);
    if(this.input.consume('e')){const npc=this.maps.currentId==='base'?this.npcs.nearest(this.player):null,facility=this.maps.currentId==='base'?this.facilities.nearby(this.player):null;if(npc){this.player.action('interact');this.openNPC(npc)}else if(facility){this.player.action('interact');facility==='storage'?this.openStorage():this.openFarm()}else{const msg=this.world.interact(this.player,{night:this.dayNight.night});if(msg){this.player.action(msg.startsWith('Coletado')||msg.startsWith('Encontrado')||msg.startsWith('Busca')?'collect':'interact');this.audio.play('pickup');this.toast(msg)}}}
    if(this.input.consume('b'))this.world.indoor?this.toast('Construa defesas apenas nas áreas externas'):this.selectBuild(this.building.mode||'barricade');
    const target=this.camera.screenToWorld(this.input.mouse.x,this.input.mouse.y);this.building.update(target,this.player,this.world);
    if(this.building.mode&&this.input.mouse.pressed){const result=this.building.confirm(this.player,this.world);this.toast(result.msg);if(result.ok)this.audio.play('pickup')}
    const farStep=this.quality==='low'?.36:this.quality==='high'?.18:.25;for(const z of this.zombies){const far=Math.hypot(z.x-this.player.x,z.y-this.player.y)>900;if(far){z.farAccum+=dt;if(z.farAccum<farStep)continue;z.update(z.farAccum,this.player,this.world,hordeHere);z.farAccum=0}else z.update(dt,this.player,this.world,hordeHere)}
    if(!this.building.mode&&(this.input.mouse.down||this.input.keys[' '])&&this.player.attackCooldown<=0){const melee=this.player.weapon.config.melee,hits=this.player.weapon.attack(target,this.zombies,this.world);this.audio.play(melee?'melee':this.player.weapon.current);for(const hit of hits)this.rewardDeath(hit);this.input.keys[' ']=false}
    for(const z of this.zombies)this.rewardDeath(z);this.zombies=this.zombies.filter(z=>!z.dead);if(this.maps.currentId==='base')this.horde.update(dt,this);
    if(this.world.base&&this.world.base.hp<=0){this.world.base.hp=30;this.player.inventory.scrap=Math.max(0,this.player.inventory.scrap-5);this.alert('A BASE FOI INVADIDA')}
    if(this.player.hp<=0){this.player.hp=this.player.maxHp;this.player.inventory.food=Math.max(0,this.player.inventory.food-1);this.survival.recoverAfterDefeat();if(this.maps.currentId!=='base'){this.changeMap({to:'base',spawn:{x:1100,y:900}});return}this.player.x=1100;this.player.y=900;this.toast('Você retornou ferido à base')}
    if(this.saveTimer>12){this.persist();this.saveTimer=0}this.updateHUD();this.input.endFrame();
  }
  rewardDeath(z){if(!z.dying||z.rewarded)return;z.rewarded=true;this.kills++;this.world.spawnDrop(z.x,z.y);if(this.player.gainXP(z.xp)){this.audio.play('level');this.toast(`Nível ${this.player.level}! +1 ponto de melhoria`)}}
  mission(){const side=this.quests.currentText(this);if(side)return side;if(this.kills<5)return`Elimine zumbis (${this.kills}/5)`;if(this.player.inventory.wood<5)return`Colete madeira (${this.player.inventory.wood}/5)`;if(this.maps.currentId!=='base')return`Explore: ${this.maps.name()} • encontre a saída marcada`;const base=this.maps.baseSnapshot(this.world);if(base.hp<75)return'Repare a base com E';if(this.world.constructions.length<2)return`Construa defesas (${this.world.constructions.length}/2)`;return'Converse com os sobreviventes na base'}
  updateHUD(){const p=this.player,w=p.weapon;$('hpBar').style.width=`${p.hp/p.maxHp*100}%`;$('stBar').style.width=`${p.stamina/p.maxStamina*100}%`;$('hungerBar').style.width=`${this.survival.hunger}%`;$('hungerBar').classList.toggle('critical',this.survival.hunger<20);$('wood').textContent=p.inventory.wood;$('scrap').textContent=p.inventory.scrap;$('food').textContent=p.inventory.food;$('meds').textContent=p.inventory.meds;$('ammo').textContent=w.config.melee?'∞':w.ammo;$('reserve').textContent=w.config.melee?'':w.reserve;$('weaponName').textContent=w.reloadLeft>0?'RECARREGANDO…':WEAPONS[w.current].name;$('weaponName').classList.toggle('reload-state',w.reloadLeft>0);$('weaponIcon').src=`assets/items/${w.current}.webp`;$('level').textContent=p.level;$('skillPoints').textContent=p.skillPoints;$('xpBar').style.width=`${p.xp/(p.level*100)*100}%`;$('clock').textContent=this.dayNight.label();$('areaName').textContent=this.maps.name();$('missionText').textContent=this.mission();const hint=this.maps.currentId==='base'?this.facilities.hint(p):'';$('contextHint').textContent=hint;$('contextHint').classList.toggle('show',!!hint);$('toast').classList.toggle('show',this.toastTimer>0);$('hordeAlert').style.opacity=this.alertTimer>0?1:0}
  toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');this.toastTimer=2.3}
  alert(msg){$('hordeAlert').innerHTML=`${msg}<small>Fortifique e defenda a casa</small>`;this.alertTimer=3.4;this.audio.play('alert')}
  toggleInventory(show){this.paused=show;const box=$('inventory'),icons={wood:'wood',scrap:'scrap',food:'food',meds:'medkit',fuel:'fuel'};box.classList.toggle('active',show);$('inventoryGrid').innerHTML=Object.entries(this.player.inventory).map(([key,value])=>`<div class="slot"><img src="assets/items/${icons[key]||key}.webp" alt=""><span>${key.toUpperCase()}</span><b>${value}</b></div>`).join('');box.querySelector('[data-close]').onclick=()=>{box.classList.remove('active');this.paused=false}}
  toggleCrafting(show){this.paused=show;const box=$('crafting');box.classList.toggle('active',show);$('craftingGrid').innerHTML=Object.entries(RECIPES).map(([id,r])=>`<button class="recipe" data-recipe="${id}"><img src="assets/items/${r.icon}.webp" alt=""><b>${r.label}</b><span>Nível ${r.level} • ${Object.entries(r.cost).map(([k,v])=>`${v} ${k}`).join(' + ')}</span></button>`).join('');box.querySelectorAll('[data-recipe]').forEach(button=>button.onclick=()=>{const result=this.crafting.craft(button.dataset.recipe,this);this.toast(result.msg);if(result.ok){this.audio.play('pickup');this.toggleCrafting(true)}});box.querySelector('[data-close]').onclick=()=>{box.classList.remove('active');this.paused=false}}
  toggleArsenal(show){this.paused=show;const box=$('arsenal'),order=['bat','pistol','axe','machete','shotgun','rifle'];box.classList.toggle('active',show);$('weaponGrid').innerHTML=order.map(name=>{const unlocked=this.player.weapon.unlocked[name];return`<button class="weapon-choice ${unlocked?'':'locked'} ${name===this.player.weapon.current?'active':''}" data-weapon="${name}" ${unlocked?'':'disabled'}><img src="assets/items/${name}.webp" alt=""><b>${WEAPONS[name].name}</b><small>${unlocked?'EQUIPAR':'BLOQUEADA'}</small></button>`}).join('');box.querySelectorAll('[data-weapon]').forEach(button=>button.onclick=()=>{if(this.player.weapon.switch(button.dataset.weapon)){this.audio.play('pickup');this.toggleArsenal(false)}});box.querySelector('[data-close]').onclick=()=>{box.classList.remove('active');this.paused=false}}
  toggleUpgrades(show){this.paused=show;const box=$('upgrades'),p=this.player;box.classList.toggle('active',show);$('upgradePoints').textContent=p.skillPoints;$('upgradeGrid').innerHTML=Object.entries(UPGRADES).map(([id,u])=>{const rank=p.upgradeRanks[id]||0,maxed=rank>=u.max;return`<button class="upgrade-choice ${maxed?'maxed':''}" data-upgrade="${id}" ${maxed||p.skillPoints<1?'disabled':''}><b>${u.name}</b><span>${u.description}</span><strong>${rank}/${u.max}</strong></button>`}).join('');box.querySelectorAll('[data-upgrade]').forEach(button=>button.onclick=()=>{const result=this.upgradeSystem.purchase(button.dataset.upgrade,this);this.toast(result.msg);if(result.ok)this.audio.play('level');this.toggleUpgrades(true)});box.querySelector('[data-close]').onclick=()=>{box.classList.remove('active');this.paused=false}}
  openStorage(){this.paused=true;const box=$('storage'),level=this.world.base?.level||1,icons={meds:'medkit'};box.classList.add('active');$('storageCapacity').textContent=`${this.facilities.used()} / ${this.facilities.capacity(level)}`;$('storageGrid').innerHTML=FACILITY_ITEMS.map(item=>`<div class="storage-row"><img src="assets/items/${icons[item]||item}.webp" alt=""><span><b>${FACILITY_LABELS[item]}</b><small>Mochila ${this.player.inventory[item]||0} • Depósito ${this.facilities.storage[item]||0}</small></span><button data-storage="withdraw" data-item="${item}" title="Retirar 1">−</button><button data-storage="deposit" data-item="${item}" title="Guardar 1">+</button></div>`).join('');box.querySelectorAll('[data-storage]').forEach(button=>button.onclick=()=>{const result=this.facilities.transfer(button.dataset.item,button.dataset.storage,1,this.player,level);this.toast(result.msg);if(result.ok)this.audio.play('pickup');this.openStorage()});box.querySelector('[data-deposit-all]').onclick=()=>{let moved=false;for(const item of FACILITY_ITEMS)moved=this.facilities.transfer(item,'deposit','all',this.player,level).ok||moved;this.toast(moved?'Itens guardados':'Nada para guardar ou depósito cheio');if(moved)this.audio.play('pickup');this.openStorage()};box.querySelector('[data-withdraw-all]').onclick=()=>{let moved=false;for(const item of FACILITY_ITEMS)moved=this.facilities.transfer(item,'withdraw','all',this.player,level).ok||moved;this.toast(moved?'Itens retirados':'O depósito está vazio');if(moved)this.audio.play('pickup');this.openStorage()};box.querySelector('[data-close]').onclick=()=>{box.classList.remove('active');this.paused=false}}
  openFarm(){this.paused=true;const box=$('farm'),level=this.world.base?.level||1,now=this.facilities.now(this.dayNight),unlocked=this.facilities.unlocked(level);box.classList.add('active');$('farmGrid').innerHTML=this.facilities.plots.map((plot,index)=>{const locked=index>=unlocked,state=locked?'locked':this.facilities.plotState(index,this.dayNight),visual=locked?'empty':state,progress=locked?0:Math.round(this.facilities.progress(index,this.dayNight)*100),remaining=plot.readyAt==null?0:Math.max(0,plot.readyAt-now),hours=Math.ceil(remaining/60),label=locked?`Libera na base nível ${index+1}`:state==='empty'?'Use 1 alimento como sementes':state==='ready'?'Pronto para colher':`${progress}% • faltam ${hours}h`,action=locked?'BLOQUEADO':state==='ready'?'COLHER +4':state==='empty'?'PLANTAR −1':'CRESCENDO';return`<button class="farm-plot ${state}" data-plot="${index}" ${locked||state==='growing'?'disabled':''}><img src="assets/props/farm/garden-${visual}.webp" alt=""><b>CANTEIRO ${index+1}</b><span>${label}</span><i><em style="width:${progress}%"></em></i><strong>${action}</strong></button>`}).join('');box.querySelectorAll('[data-plot]').forEach(button=>button.onclick=()=>{const index=+button.dataset.plot,state=this.facilities.plotState(index,this.dayNight),result=state==='ready'?this.facilities.harvest(index,this.player,this.dayNight,level):this.facilities.plant(index,this.player,this.dayNight,level);this.toast(result.msg);if(result.ok)this.audio.play(state==='ready'?'pickup':'heal');this.openFarm()});box.querySelector('[data-close]').onclick=()=>{box.classList.remove('active');this.paused=false}}
  openNPC(npc){this.paused=true;const box=$('npcDialog'),quest=QUESTS[npc.quest],state=this.quests.state(npc.quest),ready=this.quests.canComplete(npc.quest,this);$('npcName').textContent=`${npc.name} • ${npc.role}`;$('npcText').innerHTML=`${npc.greeting}<br><br><b>${quest.title}</b><br>${quest.description}<br><small>Recompensa: ${quest.reward}</small>`;const actions=[];if(state==='available')actions.push(`<button data-action="accept" class="primary">ACEITAR MISSÃO</button>`);if(ready)actions.push(`<button data-action="complete" class="primary">CONCLUIR MISSÃO</button>`);if(state==='active'&&!ready){const[p,g]=this.quests.progress(npc.quest,this);actions.push(`<button disabled>EM PROGRESSO ${p}/${g}</button>`)}actions.push(`<button data-action="trade">TROCAR RECURSOS</button>`);if(npc.id==='rook')actions.push(`<button data-action="upgrade">MELHORAR BASE • ${this.baseUpgrades.costText(this.world.base)}</button>`);$('npcActions').innerHTML=actions.join('');box.classList.add('active');const accept=box.querySelector('[data-action="accept"]'),complete=box.querySelector('[data-action="complete"]'),trade=box.querySelector('[data-action="trade"]'),upgrade=box.querySelector('[data-action="upgrade"]');if(accept)accept.onclick=()=>{const r=this.quests.accept(npc.quest,this);this.toast(r.msg);this.openNPC(npc)};if(complete)complete.onclick=()=>{const r=this.quests.complete(npc.quest,this);if(r.ok)this.audio.play('level');this.toast(r.msg);this.openNPC(npc)};if(trade)trade.onclick=()=>{const r=this.tradeNPC(npc.id);if(r.ok)this.audio.play('pickup');this.toast(r.msg);this.openNPC(npc)};if(upgrade)upgrade.onclick=()=>{const r=this.baseUpgrades.upgrade(this);if(r.ok)this.audio.play('level');this.toast(r.msg);this.openNPC(npc)};box.querySelector('[data-close]').onclick=()=>{box.classList.remove('active');this.paused=false}}
  tradeNPC(id){const p=this.player;if(id==='mara'){if(p.inventory.food<2)return{ok:false,msg:'Mara pede 2 alimentos'};p.inventory.food-=2;p.inventory.meds++;return{ok:true,msg:'Troca concluída: +1 medkit'}}if(id==='rook'){if(p.inventory.scrap<3)return{ok:false,msg:'Rook pede 3 sucatas'};p.inventory.scrap-=3;p.weapon.reserves.light+=18;return{ok:true,msg:'Troca concluída: +18 munições'}}if(p.inventory.food<2)return{ok:false,msg:'Eli pede 2 alimentos'};p.inventory.food-=2;p.weapon.reserves.rifle+=3;return{ok:true,msg:'Troca concluída: +3 munições de rifle'}}
  useMedkit(){if(this.player.inventory.meds>0&&this.player.hp<this.player.maxHp){this.player.inventory.meds--;this.player.hp=Math.min(this.player.maxHp,this.player.hp+45);this.audio.play('heal');this.toast('Medkit usado');this.toggleInventory(false);this.paused=false}}
  useFood(){const result=this.survival.eat(this.player);this.toast(result.msg);if(result.ok)this.audio.play('heal');this.toggleInventory(false);this.paused=false}
  persist(){const mapState=this.maps.serialize(this.world);SaveSystem.save({version:'0.3.0',player:this.player.serialize(),kills:this.kills,currentArea:mapState.currentArea,maps:mapState.areas,worldTime:this.dayNight.time,dayNight:this.dayNight.serialize(),horde:this.horde.serialize(),quests:this.quests.serialize(),survival:this.survival.serialize(),facilities:this.facilities.serialize()})}
  draw(){const g=this.g;g.clearRect(0,0,this.c.width,this.c.height);g.save();g.translate(-this.camera.x,-this.camera.y);this.world.drawGround(g,this.a);this.world.drawObjects(g,this.a,this.camera);this.building.draw(g,this.a);if(this.maps.currentId==='base'){this.facilities.draw(g,this.a,this.player,this.dayNight,this.world.base?.level||1);this.npcs.draw(g,this.a,this.quests,this)}const pad=180,actors=[this.player];for(const z of this.zombies)if(z.x>this.camera.x-pad&&z.x<this.camera.x+this.camera.w+pad&&z.y>this.camera.y-pad&&z.y<this.camera.y+this.camera.h+pad)actors.push(z);actors.sort((u,v)=>u.y-v.y);for(const actor of actors)actor.draw(g,this.a);this.player.weapon.draw(g,this.a);g.restore();this.dayNight.draw(g,this.c.width,this.c.height)}
}
