import { Player } from '../player/Player.js';
import { Zombie } from '../enemies/Zombie.js';
import { MapManager } from '../world/MapManager.js';
import { SaveSystem } from './SaveSystem.js';
import { Input } from './Input.js';
import { Camera } from './Camera.js';
import { AudioManager } from './AudioManager.js';
import { Settings } from './Settings.js';
import { CombatFX } from './CombatFX.js';
import { DayNightSystem } from '../systems/DayNightSystem.js';
import { HordeSystem } from '../systems/HordeSystem.js';
import { BuildingSystem } from '../systems/BuildingSystem.js';
import { CraftingSystem, RECIPES } from '../systems/CraftingSystem.js';
import { NPCSystem } from '../systems/NPCSystem.js';
import { QuestSystem, QUESTS } from '../systems/QuestSystem.js';
import { BaseUpgradeSystem } from '../systems/BaseUpgradeSystem.js';
import { SurvivalSystem } from '../systems/SurvivalSystem.js';
import { UpgradeSystem, UPGRADES } from '../systems/UpgradeSystem.js';
import { BaseFacilitiesSystem, FACILITY_ITEMS, FACILITY_LABELS } from '../systems/BaseFacilitiesSystem.js';
import { WEAPONS } from '../weapons/WeaponSystem.js';

const response=await fetch(new URL('./Game.payload.txt',import.meta.url));
const payload=(await response.text()).trim();
const bytes=Uint8Array.from(atob(payload),c=>c.charCodeAt(0));
const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));
const source=await new Response(stream).text();
const factory=new Function('Player','Zombie','MapManager','SaveSystem','Input','Camera','AudioManager','Settings','CombatFX','DayNightSystem','HordeSystem','BuildingSystem','CraftingSystem','RECIPES','NPCSystem','QuestSystem','QUESTS','BaseUpgradeSystem','SurvivalSystem','UpgradeSystem','UPGRADES','BaseFacilitiesSystem','FACILITY_ITEMS','FACILITY_LABELS','WEAPONS',`${source}; return Game;`);
export const Game=factory(Player,Zombie,MapManager,SaveSystem,Input,Camera,AudioManager,Settings,CombatFX,DayNightSystem,HordeSystem,BuildingSystem,CraftingSystem,RECIPES,NPCSystem,QuestSystem,QUESTS,BaseUpgradeSystem,SurvivalSystem,UpgradeSystem,UPGRADES,BaseFacilitiesSystem,FACILITY_ITEMS,FACILITY_LABELS,WEAPONS);
