const STATS={walker:{hp:76,speed:62,damage:11,xp:25,vision:330},runner:{hp:52,speed:125,damage:8,xp:35,vision:430},brute:{hp:230,speed:48,damage:22,xp:90,vision:280}};
export class Zombie{
  constructor(x,y,type='walker'){Object.assign(this,{x,y,type,r:type==='brute'?31:18,state:'wander',target:null,dead:false,dying:false,rewarded:false,deathTime:0,hitCd:0,hurtTime:0,attackTime:0,farAccum:0,anim:Math.random()*4,dirX:1,homeX:x,homeY:y,wanderA:Math.random()*6.28,raider:Math.random()<.38,...STATS[type]});this.maxHp=this.hp}
  hit(n){if(this.dying)return;this.hp-=n;this.hurtTime=.2;if(!this.target)this.state='alert';if(this.hp<=0){this.hp=0;this.dying=true;this.deathTime=0}}
  knockback(dx,dy,world){if(this.dying)return;world.move(this,dx,dy)}
  update(dt,p,w,horde=false){if(this.dying){this.deathTime+=dt;if(this.deathTime>1.4)this.dead=true;return}const animSpeed=this.state==='chase'?(this.type==='runner'?8.8:this.type==='brute'?4.2:5.8):(this.type==='runner'?6.5:4.1);this.anim=(this.anim+dt*animSpeed)%4;this.hitCd-=dt;this.hurtTime=Math.max(0,this.hurtTime-dt);this.attackTime=Math.max(0,this.attackTime-dt);const dp=Math.hypot(p.x-this.x,p.y-this.y),noise=w.noise;let tx,ty,baseRaid=horde&&this.raider&&w.base;if(baseRaid){tx=w.base.x+w.base.w/2;ty=w.base.y+w.base.h/2}else{if(this.state==='alert'||(this.state==='chase'&&!this.target)){this.state='chase';this.target=p}if(dp<this.vision||noise&&Math.hypot(noise.x-this.x,noise.y-this.y)<noise.radius){this.state=dp<this.vision?'chase':'investigate';this.target=this.state==='chase'?p:noise}if((this.state==='chase'||this.state==='investigate')&&this.target){tx=this.target.x;ty=this.target.y;if(this.state==='investigate'&&Math.hypot(tx-this.x,ty-this.y)<30){this.state='wander';this.target=null}}else{this.state='wander';this.target=null;this.wanderA+=dt*(Math.random()-.48);tx=this.x+Math.cos(this.wanderA)*60;ty=this.y+Math.sin(this.wanderA)*60}}
    const dx=tx-this.x,dy=ty-this.y,d=Math.hypot(dx,dy)||1;if(Math.abs(dx)>2)this.dirX=Math.sign(dx);if(baseRaid&&d<185){if(this.hitCd<=0){w.base.hp=Math.max(0,w.base.hp-this.damage*.5);this.hitCd=.9;this.attackTime=.3}return}if(!baseRaid&&dp<this.r+p.r+5){if(this.hitCd<=0){p.hit(this.damage);this.hitCd=.85;this.attackTime=.3}return}const hit=w.move(this,dx/d*this.speed*dt,dy/d*this.speed*dt);if(hit?.construction&&this.hitCd<=0){w.damageConstruction(hit.construction,this.damage);this.hitCd=.75;this.attackTime=.3}w.triggerTrap(this)}
  draw(g,a,quality='medium'){if(this.dying){const frame=Math.min(3,Math.floor(this.deathTime/1.4*4)),im=a.death(this.type,frame),s=this.type==='brute'?150:105;if(im?.complete){g.save();const fade=this.deathTime>1?Math.max(0,(1.4-this.deathTime)/.4):1;g.globalAlpha=fade;g.translate(this.x,this.y+Math.min(12,this.deathTime*9));if(this.dirX<0)g.scale(-1,1);g.drawImage(im,-s/2,-s*.72,s,s);g.restore();g.globalAlpha=1}return}const attackFrame=this.attackTime>0?Math.min(3,Math.floor((.3-this.attackTime)/.075)):Math.floor(this.anim)%4,im=this.attackTime>0?(a.attackZombie(this.type,attackFrame)||a.zombie(this.type,attackFrame)):a.zombie(this.type,attackFrame);if(im?.complete){const s=this.type==='brute'?132:86,moveBob=Math.sin(this.anim*Math.PI)*(this.state==='chase'?2.3:1.3),attackLean=this.attackTime>0?(this.type==='brute'?8:5):0,shake=this.hurtTime>0?Math.sin(this.hurtTime*90)*3:0;g.save();if(quality!=='low'){g.globalAlpha=.2;g.fillStyle='#000';g.beginPath();g.ellipse(this.x,this.y+3,s*.24,s*.07,0,0,Math.PI*2);g.fill();g.globalAlpha=1}g.translate(this.x+shake+this.dirX*attackLean,this.y+moveBob);if(this.dirX<0)g.scale(-1,1);g.drawImage(im,-s/2,-s+22,s,s);if(this.hurtTime>0&&quality==='high'){g.globalCompositeOperation='screen';g.globalAlpha=Math.min(.28,this.hurtTime*1.1);g.drawImage(im,-s/2,-s+22,s,s)}g.restore();g.globalAlpha=1;g.globalCompositeOperation='source-over'}if(quality!=='low'||this.hurtTime>0||this.hp<this.maxHp){const barW=this.type==='brute'?58:44,barY=this.type==='brute'?this.y-82:this.y-55;g.fillStyle='#231c1c';g.fillRect(this.x-barW/2,barY,barW,4);g.fillStyle=this.hurtTime>0?'#ff7768':'#b84742';g.fillRect(this.x-barW/2,barY,barW*this.hp/this.maxHp,4)}}
}
