import{CHARACTERS,STAGES,ENEMIES,WEAPONS,UPGRADES}from'../data/content.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export class Game{
constructor(canvas,save,audio,ui){this.c=canvas;this.g=canvas.getContext('2d',{alpha:false});this.save=save;this.audio=audio;this.ui=ui;this.keys={};this.pointer={x:0,y:0};this.running=false;this.paused=false;this.stage=0;this.images=new Map;this.pools={enemies:[],shots:[],gems:[],particles:[]};this.active={enemies:[],shots:[],gems:[],particles:[]};this.last=0;this.fps=60;this.joy={x:0,y:0};this.bind()}
bind(){addEventListener('keydown',e=>{this.keys[e.key.toLowerCase()]=1;if(e.key==='Escape'&&this.running)this.ui.pause()});addEventListener('keyup',e=>this.keys[e.key.toLowerCase()]=0);addEventListener('blur',()=>this.running&&this.ui.pause());this.c.onpointermove=e=>{const r=this.c.getBoundingClientRect();this.pointer={x:(e.clientX-r.left)*this.c.width/r.width,y:(e.clientY-r.top)*this.c.height/r.height}};addEventListener('gamepadconnected',()=>this.ui.toast('GAMEPAD CONECTADO'))}
async loadStage(i,progress){this.active={enemies:[],shots:[],gems:[],particles:[]};this.images.clear();const s=STAGES[i],paths=[`assets/tiles/${s.tile}.webp`,...['walker','runner','brute'].flatMap(t=>[0,1,2,3].map(n=>`assets/zombies/${t}/z-0${t==='walker'?n:t==='runner'?n+4:n+8}.webp`)),...Array.from({length:8},(_,n)=>`assets/characters/survivor/frame-0${n}.webp`),...s.props.map(p=>`assets/props/${p}.webp`)];let done=0;await Promise.all(paths.map(src=>new Promise(res=>{const im=new Image;im.onload=im.onerror=()=>{progress(++done/paths.length*100);res()};im.src=src;this.images.set(src,im)})));this.stage=i}
start(i=0){this.stage=i;const ch=CHARACTERS.find(x=>x.id===this.save.selected)||CHARACTERS[0],perk=this.save.perks,diff=this.save.settings.difficulty;this.player={x:1600,y:1600,r:18,hp:ch.hp+(perk.health||0)*6,max:ch.hp+(perk.health||0)*6,speed:ch.speed*(1+(perk.speed||0)*.025),damage:ch.damage||1,crit:ch.crit||.05,regen:ch.regen||0,weapon:ch.weapon,fire:0,special:0,invuln:0,anim:0,face:1};this.run={time:0,kills:0,scrap:0,level:1,xp:0,next:28,ranks:{},rerolls:1+(perk.reroll||0),damage:0,taken:0,boss:null,bossHit:false,spawnQ:[],event:0,turrets:[]};this.diff=diff==='nightmare'?1.45:diff==='hard'?1.22:1;this.running=true;this.paused=false;this.last=performance.now();this.save.stats.runs++;this.save.stats.characters[ch.id]=(this.save.stats.characters[ch.id]||0)+1;this.audio.wake();requestAnimationFrame(t=>this.loop(t));this.ui.sync()}
loop(t){if(!this.running)return;let dt=Math.min(.033,(t-this.last)/1000||.016);this.last=t;this.fps=this.fps*.96+(1/dt)*.04;if(!this.paused)this.update(dt);this.draw(t/1000);requestAnimationFrame(x=>this.loop(x))}
quality(){let q=this.save.settings.quality;if(q==='auto')q=this.fps<42?'low':this.fps<55?'medium':'high';return q}
limit(){return{low:60,medium:100,high:150}[this.quality()]||100}
axis(){let x=(this.keys.d||this.keys.arrowright?1:0)-(this.keys.a||this.keys.arrowleft?1:0)+this.joy.x,y=(this.keys.s||this.keys.arrowdown?1:0)-(this.keys.w||this.keys.arrowup?1:0)+this.joy.y;const gp=navigator.getGamepads?.()[0];if(gp){x+=Math.abs(gp.axes[0])>.18?gp.axes[0]:0;y+=Math.abs(gp.axes[1])>.18?gp.axes[1]:0;if(gp.buttons[0].pressed)this.special()}const l=Math.hypot(x,y)||1;return{x:x/l,y:y/l,m:l>.15}}
spawn(type){if(this.active.enemies.length>=this.limit()){this.run.spawnQ.push(type);return}const a=Math.random()*Math.PI*2,d=rnd(520,700),e=this.pools.enemies.pop()||{};Object.assign(e,ENEMIES[type]||ENEMIES.walker,{type,x:this.player.x+Math.cos(a)*d,y:this.player.y+Math.sin(a)*d,dead:false,hurt:0,anim:rnd(0,4),cool:0,max:(ENEMIES[type]||ENEMIES.walker).hp*this.diff,hp:(ENEMIES[type]||ENEMIES.walker).hp*this.diff});this.active.enemies.push(e);this.save.bestiary[type]=(this.save.bestiary[type]||0)+0}
boss(){if(this.run.boss)return;this.run.spawnQ.length=0;const names=STAGES[this.stage].boss,e={type:'boss',name:names,x:this.player.x+600,y:this.player.y,hp:(1700+this.stage*800)*this.diff,max:(1700+this.stage*800)*this.diff,speed:34+this.stage*5,dmg:22+this.stage*4,r:64,scale:2.35,sprite:'brute',cool:2,phase:1,anim:0,dead:false,hurt:0,xp:250};this.run.boss=e;this.active.enemies.push(e);this.audio.boss();this.ui.toast(names.toUpperCase())}
fire(){const p=this.player,w=WEAPONS[p.weapon],target=this.active.enemies.filter(e=>!e.dead).sort((a,b)=>dist(a,p)-dist(b,p))[0];if(!target)return;p.fire=w.rate/(1+(this.run.ranks.rate||0)*.1);const dmg=w.damage*p.damage*(1+(this.save.perks.damage||0)*.03)*(1+(this.run.ranks.damage||0)*.12),count=w.count+(this.run.ranks.projectile||0);if(w.melee){for(const e of this.active.enemies)if(dist(e,p)<w.area*(1+(this.run.ranks.area||0)*.15))this.hit(e,dmg);this.burst(p.x,p.y,'#efffba',12);this.audio.shot(p.weapon);return}const base=Math.atan2(target.y-p.y,target.x-p.x);for(let i=0;i<count;i++){const a=base+(i-(count-1)/2)*(w.spread||.09),b=this.pools.shots.pop()||{};Object.assign(b,{x:p.x,y:p.y,vx:Math.cos(a)*w.speed,vy:Math.sin(a)*w.speed,life:1.25,dmg,pierce:w.pierce+(this.run.ranks.pierce||0),dead:false});this.active.shots.push(b)}this.audio.shot(p.weapon);this.save.stats.weapons[p.weapon]=(this.save.stats.weapons[p.weapon]||0)+1}
hit(e,dmg){const crit=Math.random()<this.player.crit+(this.save.perks.crit||0)*.02+(this.run.ranks.crit||0)*.08,n=dmg*(crit?2:1);e.hp-=n;e.hurt=.1;this.run.damage+=n;this.audio.hit(crit);if(this.save.settings.damageNumbers)this.particle(e.x,e.y-25,crit?'#fff07a':'#fff',`${Math.round(n)}`);if(e.hp<=0&&!e.dead){e.dead=true;this.run.kills++;this.run.scrap+=Math.random()<.18?1:0;this.save.stats.kills++;this.save.bestiary[e.type]=(this.save.bestiary[e.type]||0)+1;const gem=this.pools.gems.pop()||{};Object.assign(gem,{x:e.x,y:e.y,v:Math.round(e.xp||8),dead:false});this.active.gems.push(gem);this.burst(e.x,e.y,'#9e2828',this.quality()==='low'?3:8);if(e===this.run.boss)this.victory();else if(this.player.explode&&Math.random()<this.player.explode)this.explode(e.x,e.y,n*.6)}}
explode(x,y,d){this.burst(x,y,'#ca70ff',18);for(const e of this.active.enemies)if(!e.dead&&Math.hypot(e.x-x,e.y-y)<130)this.hit(e,d)}
particle(x,y,color,n){const p=this.pools.particles.pop()||{};Object.assign(p,{x,y,color,text:n,vx:rnd(-20,20),vy:rnd(-65,-25),life:.65,max:.65});this.active.particles.push(p)}
burst(x,y,color,n){for(let i=0;i<n;i++){const p=this.pools.particles.pop()||{},a=Math.random()*6.28,s=rnd(30,150);Object.assign(p,{x,y,color,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rnd(.2,.55),max:.55});this.active.particles.push(p)}}
gain(v){this.run.xp+=v*(1+(this.save.perks.xp||0)*.05);if(this.run.xp>=this.run.next){this.run.xp-=this.run.next;this.run.level++;this.run.next=Math.round(this.run.next*1.22+8);this.save.stats.maxLevel=Math.max(this.save.stats.maxLevel,this.run.level);this.paused=true;this.audio.level();this.ui.upgrades()}}
special(){const p=this.player;if(p.special>0)return;p.special=18;const id=this.save.selected;if(id==='medic'){p.hp=Math.min(p.max,p.hp+55);this.burst(p.x,p.y,'#8ef0bd',22)}else if(id==='engineer'){this.run.turrets.push({x:p.x,y:p.y,life:14,fire:0})}else if(id==='survivor'){p.rage=7}else if(id==='agent'){for(const e of this.active.enemies)this.hit(e,55)}else{const nearest=this.active.enemies.filter(e=>!e.dead).slice(0,id==='hunter'?8:16);nearest.forEach(e=>this.hit(e,id==='hunter'?90:42))}this.ui.toast('ESPECIAL ATIVADO')}
update(dt){const p=this.player,r=this.run,a=this.axis();this.lastAxis=a;p.x=clamp(p.x+a.x*p.speed*dt,80,3120);p.y=clamp(p.y+a.y*p.speed*dt,80,3120);p.anim+=dt*(a.m?8:2);if(a.m)p.face=a.x<0?-1:1;p.fire-=dt;p.special-=dt;p.invuln-=dt;p.hp=Math.min(p.max,p.hp+(p.regen+(this.save.perks.regen||0)*.12+(this.run.ranks.regen||0)*.25)*dt);if(p.rage>0)p.rage-=dt;if(p.fire<=0)this.fire();r.time+=dt;this.save.stats.time+=dt;r.event+=dt;const rate=Math.max(.12,.82-r.time/420),waves=1+Math.floor(r.time/60);if(!r.boss&&r.time<300&&(r.event>rate)){r.event=0;for(let i=0;i<Math.min(4,waves);i++){const list=STAGES[this.stage].types.slice(0,Math.min(3,1+Math.floor(r.time/75)));this.spawn(list[Math.floor(Math.random()*list.length)])}}if(r.time>=300&&!r.boss)this.boss();if(r.spawnQ.length&&this.active.enemies.length<this.limit())this.spawn(r.spawnQ.shift());
for(const s of this.active.shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(s.life<=0)s.dead=true;for(const e of this.active.enemies)if(!e.dead&&Math.hypot(s.x-e.x,s.y-e.y)<e.r+5){this.hit(e,s.dmg);if(s.pierce--<=0){s.dead=true;break}}}
for(const e of this.active.enemies){if(e.dead)continue;e.anim+=dt*(e.type==='boss'?3:5);e.hurt-=dt;e.cool-=dt;const dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy)||1;if(e===r.boss){e.phase=e.hp/e.max<.4?3:e.hp/e.max<.72?2:1;if(e.cool<=0){e.cool=3/e.phase;this.burst(e.x,e.y,'#9cde55',10);for(let i=0;i<e.phase*2;i++)this.spawn(STAGES[this.stage].types[i%3])}e.speed=35+e.phase*16}else if(e.dash&&e.cool<=0){e.speed*=2.5;e.cool=3}e.x+=dx/d*e.speed*dt;e.y+=dy/d*e.speed*dt;if(d<e.r+p.r&&p.invuln<=0){const dmg=e.dmg*this.diff;p.hp-=dmg;r.taken+=dmg;p.invuln=.55;this.burst(p.x,p.y,'#e05b50',7);if(e===r.boss)r.bossHit=true;if(p.hp<=0)this.gameOver()}}
const magnet=110*(1+(this.save.perks.magnet||0)*.08+(r.ranks.magnet||0)*.25);for(const x of this.active.gems){const d=dist(x,p);if(d<magnet){x.x+=(p.x-x.x)/Math.max(1,d)*380*dt;x.y+=(p.y-x.y)/Math.max(1,d)*380*dt}if(d<28){x.dead=true;this.gain(x.v)}}
for(const t of r.turrets){t.life-=dt;t.fire-=dt;if(t.fire<=0){const e=this.active.enemies.find(e=>!e.dead&&dist(e,t)<420);if(e){this.hit(e,24*(CHARACTERS.find(c=>c.id===this.save.selected).turret||1));t.fire=.22}}}
for(const p of this.active.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}
this.clean('shots');this.clean('gems');this.clean('particles');const dead=this.active.enemies.filter(e=>e.dead);this.active.enemies=this.active.enemies.filter(e=>!e.dead);dead.forEach(e=>this.pools.enemies.push(e));r.turrets=r.turrets.filter(t=>t.life>0);this.ui.sync()}
clean(k){const dead=this.active[k].filter(x=>x.dead||x.life<=0);this.active[k]=this.active[k].filter(x=>!(x.dead||x.life<=0));dead.forEach(x=>this.pools[k].push(x))}
victory(){this.running=false;const r=this.run,reward=40+this.stage*25+r.scrap;this.save.scrap+=reward;this.save.dna+=5+this.stage*3;this.save.stats.bosses++;this.save.stats.wins++;this.save.campaign=Math.max(this.save.campaign,Math.min(5,this.stage+2));if(this.stage===4&&!this.save.unlocked.includes('agent'))this.save.unlocked.push('agent');this.save.achievements.survivor=true;if(!r.bossHit)this.save.achievements.untouchable=true;this.ui.result(true,reward)}
gameOver(){this.running=false;this.save.scrap+=Math.floor(this.run.scrap/2);this.ui.result(false,Math.floor(this.run.scrap/2))}
stop(){this.running=false}
draw(t){const g=this.g,c=this.c,p=this.player,s=STAGES[this.stage];g.fillStyle=s.tint;g.fillRect(0,0,c.width,c.height);const cam={x:p.x-c.width/2,y:p.y-c.height/2};const tile=this.images.get(`assets/tiles/${s.tile}.webp`);if(tile?.complete)for(let x=Math.floor(cam.x/256)*256;x<cam.x+c.width+256;x+=256)for(let y=Math.floor(cam.y/256)*256;y<cam.y+c.height+256;y+=256)g.drawImage(tile,x-cam.x,y-cam.y,258,258);g.fillStyle='#0003';for(let x=200;x<3200;x+=430)for(let y=170;y<3200;y+=510){if(x<cam.x-120||x>cam.x+c.width+120||y<cam.y-120||y>cam.y+c.height+120)continue;g.fillRect(x-cam.x-35,y-cam.y-20,70,40)}
const drawSprite=(e)=>{const type=e.sprite||'walker',start=type==='runner'?4:type==='brute'?8:0,n=start+Math.floor(e.anim)%4,path=`assets/zombies/${type}/z-${String(n).padStart(2,'0')}.webp`,im=this.images.get(path),sz=78*(e.scale||1);g.save();g.translate(e.x-cam.x,e.y-cam.y);if(e.hurt>0)g.globalAlpha=.55;if(im?.complete)g.drawImage(im,-sz/2,-sz*.72,sz,sz);else{g.fillStyle='#6e8b55';g.fillRect(-18,-35,36,55)}g.restore();if(e.type==='boss'){g.fillStyle='#ce524c';g.fillRect(e.x-cam.x-45,e.y-cam.y-62,90*e.hp/e.max,5)}};
for(const x of this.active.gems){g.fillStyle='#65baff';g.beginPath();g.arc(x.x-cam.x,x.y-cam.y,5+Math.sin(t*5)*1.5,0,7);g.fill()}for(const e of this.active.enemies)drawSprite(e);for(const s of this.active.shots){g.fillStyle='#ffe89a';g.beginPath();g.arc(s.x-cam.x,s.y-cam.y,3,0,7);g.fill()}for(const q of this.run.turrets){g.fillStyle='#d8bb59';g.fillRect(q.x-cam.x-13,q.y-cam.y-13,26,26)}
const ch=CHARACTERS.find(x=>x.id===this.save.selected),im=this.images.get(`assets/characters/survivor/frame-0${this.lastAxis?.m?4+Math.floor(p.anim)%4:Math.floor(p.anim)%4}.webp`);g.save();g.translate(c.width/2,c.height/2);g.scale(p.face,1);if(im?.complete){g.filter=`drop-shadow(0 8px 5px #000) sepia(.25) hue-rotate(${CHARACTERS.indexOf(ch)*45}deg)`;g.drawImage(im,-50,-72,100,100)}else{g.fillStyle=ch.color;g.fillRect(-18,-42,36,60)}g.restore();for(const q of this.active.particles){g.globalAlpha=clamp(q.life/q.max,0,1);g.fillStyle=q.color;if(q.text){g.font='bold 16px Arial';g.fillText(q.text,q.x-cam.x,q.y-cam.y)}else g.fillRect(q.x-cam.x,q.y-cam.y,3,3)}g.globalAlpha=1}
}