import { WeaponSystem } from '../weapons/WeaponSystem.js';
export class Player{
  constructor(x,y,save={}){this.x=save.x??x;this.y=save.y??y;this.r=20;this.inventory={wood:0,scrap:0,food:0,meds:1,fuel:0,...save.inventory};this.level=save.level??1;this.xp=save.xp??0;this.upgradeRanks={vitality:0,endurance:0,power:0,reload:0,mobility:0,metabolism:0,...save.upgrades};const spent=Object.values(this.upgradeRanks).reduce((sum,n)=>sum+n,0);this.skillPoints=save.skillPoints??Math.max(0,this.level-1-spent);this.recalculateStats();this.hp=Math.min(this.maxHp,save.hp??this.maxHp);this.stamina=this.maxStamina;this.attackCooldown=0;this.anim=0;this.moving=false;this.face=0;this.hurtTime=0;this.actionTime=0;this.actionFrame=13;this.aimTime=0;this.weapon=new WeaponSystem(this,save.weapon||{})}
  recalculateStats(){this.maxHp=100+this.upgradeRanks.vitality*15;this.maxStamina=100+this.upgradeRanks.endurance*12;this.speed=205*(1+this.upgradeRanks.mobility*.04);this.damageMultiplier=1+this.upgradeRanks.power*.12;this.reloadMultiplier=1+this.upgradeRanks.reload*.12;this.hungerMultiplier=Math.pow(.85,this.upgradeRanks.metabolism)}
  update(dt,input,world){const v=input.axis();this.moving=Math.hypot(v.x,v.y)>.1;if(this.moving){world.move(this,v.x*this.speed*dt,v.y*this.speed*dt);this.anim=(this.anim+dt*7*(this.speed/205))%4;this.face=Math.abs(v.x)>Math.abs(v.y)?(v.x>0?1:3):(v.y>0?0:2)}this.hurtTime=Math.max(0,this.hurtTime-dt);this.actionTime=Math.max(0,this.actionTime-dt);this.aimTime=Math.max(0,this.aimTime-dt);this.attackCooldown=Math.max(0,this.attackCooldown-dt);this.stamina=Math.min(this.maxStamina,this.stamina+(17+this.upgradeRanks.endurance*1.4)*dt);this.weapon.update(dt)}
  hit(dmg){this.hp=Math.max(0,this.hp-dmg);this.hurtTime=.24}aimAt(x,y){const dx=x-this.x,dy=y-this.y;if(Math.abs(dx)>Math.abs(dy))this.face=dx>0?1:3;else this.face=dy>0?0:2;this.aimTime=.3}action(type='interact'){this.actionFrame=type==='collect'?14:13;this.actionTime=.32}
  gainXP(n){this.xp+=n;let gained=0;while(this.xp>=this.level*100){this.xp-=this.level*100;this.level++;this.skillPoints++;gained++}if(gained)this.hp=this.maxHp;return gained}
  draw(g,a,quality='medium'){const weapon=this.weapon.current,advanced=['axe','machete','shotgun','rifle'].includes(weapon);let im,size=94,flip=false;if(this.hurtTime>0){im=a.player(13);flip=this.face===3}else if(this.actionTime>0){im=a.player(this.actionFrame);flip=this.face===3}else if(advanced&&this.attackCooldown>0){const duration=this.weapon.config.cooldown,frame=Math.min(3,Math.floor((1-this.attackCooldown/duration)*4));im=a.playerWeapon(weapon,frame);size=105;flip=this.face===3}else if(this.attackCooldown>.18&&weapon==='bat'){im=a.player(8+(Math.floor((.48-this.attackCooldown)*10)%4));flip=this.face===3}else if(this.moving){im=a.player(4+Math.floor(this.anim)%4);flip=this.face===3}else im=a.player(this.face);if(im?.complete){const bob=this.moving?Math.sin(this.anim*Math.PI)*1.8:0;g.save();if(quality!=='low'){g.globalAlpha=.24;g.fillStyle='#000';g.beginPath();g.ellipse(this.x,this.y+4,size*.27,size*.095,0,0,Math.PI*2);g.fill();g.globalAlpha=1}g.translate(this.x,this.y+bob);if(flip)g.scale(-1,1);g.drawImage(im,-size/2,-size*.76,size,size);g.restore()}}
  serialize(){return{x:this.x,y:this.y,hp:this.hp,inventory:this.inventory,level:this.level,xp:this.xp,skillPoints:this.skillPoints,upgrades:this.upgradeRanks,weapon:this.weapon.serialize()}}
}
