import {CollisionSystem} from '../systems/CollisionSystem.js';
import {LootSystem} from '../systems/LootSystem.js';
import {MAPS} from './MapData.js';

export class World{
  constructor(save={},area='base'){
    const data=MAPS[area]||MAPS.base;this.area=area;this.name=data.name;this.w=data.w;this.h=data.h;this.tile=data.tile;this.exits=data.exits;this.indoor=!!data.indoor;this.margin=this.indoor?46:0;this.population=data.population??1;this.noise=null;this.noiseLife=0;this.loot=new LootSystem();this._collisionCache=null;this._groundPattern=null;
    if(data.base){const level=Math.max(1,Math.min(3,save.baseLevel??1)),maxHp=[0,100,145,210][level];this.base={...data.base,level,maxHp,hp:Math.min(maxHp,save.baseHp??55)}}else this.base=null;
    this.drops=[];const used=new Set(save.looted||[]);this.containers=data.containers.map(([sprite,x,y,size,persistent],index)=>({id:`${area}-${index}`,sprite,x,y,size,persistent:!!persistent,used:used.has(`${area}-${index}`)||used.has(index)}));this.props=data.props.map(prop=>[...prop]);this.blockers=data.blockers.map(o=>({...o}));this.constructions=(save.constructions||[]).map(c=>({...c,hp:c.hp??c.maxHp}));
  }
  makeNoise(x,y,radius){this.noise={x,y,radius};this.noiseLife=.8}
  update(dt){this.noiseLife-=dt;if(this.noiseLife<=0)this.noise=null}
  collisionObjects(){if(!this._collisionCache)this._collisionCache=[...this.blockers,...this.constructions.filter(c=>c.type!=='trap').map(c=>({...c,construction:c}))];return this._collisionCache}
  isBlocked(x,y,r){return!!CollisionSystem.hit(x,y,r,this.collisionObjects())}
  overlapsExit(rect){return this.exits.some(e=>rect.x<e.x+e.w&&rect.x+rect.w>e.x&&rect.y<e.y+e.h&&rect.y+rect.h>e.y)}
  move(entity,dx,dy){const hit=CollisionSystem.move(entity,dx,dy,this.collisionObjects());entity.x=Math.max(entity.r+this.margin,Math.min(this.w-entity.r-this.margin,entity.x));entity.y=Math.max(entity.r+this.margin,Math.min(this.h-entity.r-this.margin,entity.y));return hit}
  addConstruction(c){this.constructions.push(c);this._collisionCache=null}
  damageConstruction(c,n){c.hp-=n;if(c.hp<=0){this.constructions.splice(this.constructions.indexOf(c),1);this._collisionCache=null}}
  triggerTrap(z){const trap=this.constructions.find(c=>c.type==='trap'&&CollisionSystem.circleRect(z.x,z.y,z.r,c));if(!trap)return false;z.hit(95);this.constructions.splice(this.constructions.indexOf(trap),1);this._collisionCache=null;return true}
  spawnDrop(x,y){const types=['wood','scrap','food','meds'];this.drops.push({x,y,t:types[Math.floor(Math.random()*types.length)]})}
  interact(p,{night=false}={}){for(let i=this.drops.length-1;i>=0;i--){const d=this.drops[i];if(Math.hypot(d.x-p.x,d.y-p.y)<60){p.inventory[d.t]++;this.drops.splice(i,1);return`Coletado: ${d.t}`}}for(const c of this.containers){if(!c.used&&Math.hypot(c.x-p.x,c.y-p.y)<90){c.used=true;return this.loot.open(c,p,night)}}const b=this.base;if(b&&p.x>b.x-60&&p.x<b.x+b.w+60&&p.y>b.y-60&&p.y<b.y+b.h+60&&b.hp<b.maxHp){if(p.inventory.wood>=2){p.inventory.wood-=2;b.hp=Math.min(b.maxHp,b.hp+20);return'Base reparada'}return'Madeira insuficiente (2)'}return null}
  drawGround(g,a){const image=a.tile(this.tile);if(!this._groundPattern&&image?.complete&&g.createPattern)this._groundPattern=g.createPattern(image,'repeat');g.fillStyle=this._groundPattern||'#3f4941';g.fillRect(0,0,this.w,this.h);g.save();if(this.indoor){g.fillStyle='#151713';g.fillRect(0,0,this.w,46);g.fillRect(0,this.h-46,this.w,46);g.fillRect(0,0,46,this.h);g.fillRect(this.w-46,0,46,this.h);g.strokeStyle='#434a42';g.lineWidth=5;g.strokeRect(46,46,this.w-92,this.h-92)}for(const exit of this.exits){const horizontal=exit.w>exit.h,gx=exit.x+exit.w/2,gy=exit.y+exit.h/2;g.fillStyle='#b7d35b33';g.fillRect(exit.x,exit.y,exit.w,exit.h);g.strokeStyle='#b7d35b';g.lineWidth=4;g.strokeRect(exit.x+5,exit.y+5,exit.w-10,exit.h-10);g.fillStyle='#eef5e9';g.font='bold 15px Segoe UI';g.textAlign='center';g.fillText(exit.label,gx,horizontal?gy:exit.y+28)}g.restore()}
  drawObjects(g,a,view=null){const visible=(x,y,pad=220)=>!view||x>view.x-pad&&x<view.x+view.w+pad&&y>view.y-pad&&y<view.y+view.h+pad,b=this.base;if(b&&visible(b.x+b.w/2,b.y+b.h/2,300)){const im=a.base(b.level)||a.prop('base');if(im?.complete)g.drawImage(im,b.x-32,b.y-5,b.w+64,b.h);g.fillStyle='#211d1c';g.fillRect(b.x,b.y-24,b.w,9);g.fillStyle='#b4443f';g.fillRect(b.x,b.y-24,b.w*b.hp/b.maxHp,9)}const all=[...this.props,...this.containers.filter(c=>!c.used||c.persistent).map(c=>[c.sprite,c.x,c.y,c.size])].filter(([,x,y])=>visible(x,y)).sort((u,v)=>u[2]-v[2]);for(const[name,x,y,s]of all){const pic=a.prop(name);if(pic?.complete)g.drawImage(pic,x-s/2,y-s*.72,s,s)}for(const c of this.constructions){if(!visible(c.x,c.y))continue;const pic=a.prop(c.type),ratio=c.hp/c.maxHp;g.globalAlpha=.55+.45*ratio;if(pic?.complete)g.drawImage(pic,c.x,c.y-c.h*1.7,c.w,c.h*2.7);g.globalAlpha=1;if(c.type!=='trap'&&ratio<1){g.fillStyle='#241a19';g.fillRect(c.x,c.y-9,c.w,5);g.fillStyle='#c55b4e';g.fillRect(c.x,c.y-9,c.w*ratio,5)}}for(const d of this.drops){if(!visible(d.x,d.y))continue;const pic=a.item(d.t==='meds'?'medkit':d.t);if(pic?.complete)g.drawImage(pic,d.x-20,d.y-25,40,40)}}
  serialize(){return{baseHp:this.base?.hp,baseLevel:this.base?.level,looted:this.containers.filter(c=>c.used).map(c=>c.id),constructions:this.constructions.map(c=>({...c}))}}
}
